// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAbBufdzs-vqaZ8HEeLCNmfJgLRK3lPN8',
    appId: '1:786640143654:web:928a7825a232d9bf9fade7',
    messagingSenderId: '786640143654',
    projectId: 'gymbot-3ddf3',
    authDomain: 'gymbot-3ddf3.firebaseapp.com',
    databaseURL: 'https://gymbot-3ddf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gymbot-3ddf3.firebasestorage.app',
    measurementId: 'G-0STFJVVL4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrnXQSy418UDWssfZf9UUanaBdoPlatvQ',
    appId: '1:786640143654:android:b765553d6f92250f9fade7',
    messagingSenderId: '786640143654',
    projectId: 'gymbot-3ddf3',
    databaseURL: 'https://gymbot-3ddf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gymbot-3ddf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2VmzosI_gkbaJYcm55pXB9pvN7SbtPwo',
    appId: '1:786640143654:ios:0a211b36f39efa5d9fade7',
    messagingSenderId: '786640143654',
    projectId: 'gymbot-3ddf3',
    databaseURL: 'https://gymbot-3ddf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gymbot-3ddf3.firebasestorage.app',
    androidClientId: '786640143654-kjnodvvjphqn7bt1h9hk5g78d8pp0gtd.apps.googleusercontent.com',
    iosClientId: '786640143654-guhi0akc8m4261ggcnd8op751gcf4t6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymFitnessMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2VmzosI_gkbaJYcm55pXB9pvN7SbtPwo',
    appId: '1:786640143654:ios:0a211b36f39efa5d9fade7',
    messagingSenderId: '786640143654',
    projectId: 'gymbot-3ddf3',
    databaseURL: 'https://gymbot-3ddf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gymbot-3ddf3.firebasestorage.app',
    androidClientId: '786640143654-kjnodvvjphqn7bt1h9hk5g78d8pp0gtd.apps.googleusercontent.com',
    iosClientId: '786640143654-guhi0akc8m4261ggcnd8op751gcf4t6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymFitnessMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAbBufdzs-vqaZ8HEeLCNmfJgLRK3lPN8',
    appId: '1:786640143654:web:46eaf601352fb4509fade7',
    messagingSenderId: '786640143654',
    projectId: 'gymbot-3ddf3',
    authDomain: 'gymbot-3ddf3.firebaseapp.com',
    databaseURL: 'https://gymbot-3ddf3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gymbot-3ddf3.firebasestorage.app',
    measurementId: 'G-TSHLRBLT56',
  );
}
